name: Bug report
description: Create a report to help us improve
labels: [bug]
body:
  - type: input
    id: extension-version
    attributes:
      label: Extension version
      placeholder: e.g. 1.2.0
    validations:
      required: false

  - type: input
    id: vs-version
    attributes:
      label: Visual Studio version
      placeholder: e.g. Visual Studio 2022 17.9.0
    validations:
      required: false

  - type: dropdown
    id: install-source
    attributes:
      label: Install source
      options:
        - Visual Studio Marketplace
        - Open VSIX Gallery
        - Built from source
        - Other
    validations:
      required: false

  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      placeholder: A clear and concise description of what you expected to happen.
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual behavior
      placeholder: A clear and concise description of what actually happened.
    validations:
      required: true

  - type: textarea
    id: error-message
    attributes:
      label: Error message / call stack
      description: If applicable, paste any error messages or stack traces here.
      render: text
    validations:
      required: false

  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Add any other context, screenshots, or information about the problem here.
    validations:
      required: false
