// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer 1.0.45
//     Available from https://marketplace.visualstudio.com/items?itemName=MadsKristensen.VsixSynchronizer64
// </auto-generated>
// ------------------------------------------------------------------------------
namespace ScratchFiles
{
    using System;

    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string ScratchFilesString = "04fc2f76-aec6-4077-aeff-121520f4dcfa";
        public static Guid ScratchFiles = new Guid(ScratchFilesString);

        public const string ScratchFilesToolWindowString = "a1b2c3d4-e5f6-4a7b-8c9d-0e1f2a3b4c5d";
        public static Guid ScratchFilesToolWindow = new Guid(ScratchFilesToolWindowString);
    }

    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int ToolWindowToolbar = 0x0010;
        public const int TreeContextMenu = 0x0011;
        public const int FileMenuGroup = 0x0001;
        public const int ViewMenuGroup = 0x0002;
        public const int SolutionContextMenuGroup = 0x0003;
        public const int ToolWindowToolbarNewGroup = 0x0004;
        public const int ToolWindowToolbarActionsGroup = 0x0005;
        public const int TreeContextMenuGroup = 0x0006;
        public const int TreeContextMenuDeleteGroup = 0x0007;
        public const int NewGlobalScratchFile = 0x0106;
        public const int NewSolutionScratchFile = 0x0101;
        public const int ShowToolWindow = 0x0102;
        public const int ToolbarNewGlobal = 0x0103;
        public const int ToolbarNewSolution = 0x0104;
        public const int ToolbarOpenFolder = 0x0105;
        public const int ContextOpen = 0x0110;
        public const int ContextRename = 0x0111;
        public const int ContextDelete = 0x0112;
        public const int ContextOpenFolder = 0x0113;
    }
}
